## Autogenerated from /home/andrzej/GitHub/llvm-tutor/tests/lit.site.cfg.py.in
## Do not edit!

import sys

config.target_triple = "x86_64-unknown-linux-gnu"
config.llvm_obj_root = "/home/andrzej/llvm/build"
config.llvm_tools_dir = "/home/andrzej/llvm/build/bin/"
config.llvm_lib_dir = "/home/andrzej/llvm/build/./lib"

# Support substitution of the tools_dir with user parameters. This is
# used when we can't determine the tool dir at configuration time.
try:
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
except KeyError:
    e = sys.exc_info()[1]
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, "/home/andrzej/GitHub/llvm-tutor/tests/lit.cfg.py")
